[env:disco_b_g431b_esc1]
platform = ststm32
board = disco_b_g431b_esc1
framework = arduino
monitor_speed = 115200
lib_archive = false
build_flags =
    -DHAL_OPAMP_MODULE_ENABLED
lib_deps =
    askuric/Simple FOC @ 2.3.1
    SPI
    Wire