[env:J01]
platform = ststm32@17.6.0
board = disco_b_g431b_esc1
framework = arduino
monitor_speed = 921600
lib_archive = false
build_flags =
    -DHAL_OPAMP_MODULE_ENABLED
    -D HAL_FDCAN_MODULE_ENABLED

