#pragma once
// ============================================================================
// can_proto_vectors.h -- golden vectors for can_proto.h. (CAN-T0, 2026-10-03)
// ============================================================================
// Run by BOTH tiers (Tier-0 console 't', master console 't', and once at boot
// on each), so the packing is checked on each compiler independently. PURE:
// returns a fail count and the first failing case number; the caller prints.
//
// The expected BYTES were computed by an independent Python implementation of
// the spec in can_proto.h's header, not by this code -- a vector generated by
// the code under test only proves the code agrees with itself. Every input was
// also checked to land >= 0.1 LSB away from a rounding half in float32 (e.g.
// 1.123 rad/s / 0.002 = 561.5 exactly was replaced by 1.124), so the vectors
// test the layout, not the rounding direction of one platform's divide.
// ============================================================================
#include "can_proto.h"

struct CanCmdVector   { MitCmd c;   uint8_t bytes[8]; };
struct CanStateVector { MitState s; uint8_t status; uint8_t bytes[8]; };

static const CanCmdVector CAN_CMD_VECTORS[] = {
  // a5-like command: p_des 1 rad, v_des -2, kp 41, kd 0.157, ff -0.39
  { { 1.0f, -2.0f, 41.0f, 0.157f, -0.39f },
    { 0x5F, 0x14, 0x9C, 0xAF, 0x19, 0x9D, 0x20, 0xFB } },
  // every field near its positive end (and p_des negative): range + sign ext
  { { -6.0f, 40.94f, 409.5f, 4.095f, 10.235f },
    { 0xC5, 0x85, 0xFF, 0xF7, 0xFF, 0xFF, 0xFF, 0x7F } },
  // a5 step size with zero v_des and zero ff
  { { 0.0284f, 0.0f, 10.0f, 0.1f, 0.0f },
    { 0x94, 0x00, 0x00, 0x40, 0x06, 0x64, 0x00, 0x00 } },
  // ZERO IS ZERO: the all-zero command is the all-zero frame
  { { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
    { 0, 0, 0, 0, 0, 0, 0, 0 } },
};

static const CanStateVector CAN_STATE_VECTORS[] = {
  // one motor rev of output (40 deg), a3-like speed, armed / HOLD / fault 3
  { { 0.6981f, -1.124f, 0.0882f }, 0x33,
    { 0xB2, 0x10, 0x01, 0xCE, 0xFD, 0xB0, 0x00, 0x33 } },
  { { -50.0f, 65.0f, -16.0f }, 0x00,
    { 0xC0, 0xB4, 0xB3, 0xF4, 0x7E, 0x00, 0x83, 0x00 } },
};

// Commands the packer MUST refuse (non-finite or not representable).
static const MitCmd CAN_CMD_REJECTS[] = {
  {  NAN,       0.0f,   0.0f,   0.0f,   0.0f   },
  {  0.0f,  INFINITY,   0.0f,   0.0f,   0.0f   },
  {  6.2832f,   0.0f,   0.0f,   0.0f,   0.0f   },   // 2*pi is one LSB past int16
  {  0.0f,     41.0f,   0.0f,   0.0f,   0.0f   },   // v_des range end is 40.96
  {  0.0f,      0.0f,  -0.1f,   0.0f,   0.0f   },   // negative gain
  {  0.0f,      0.0f, 409.6f,   0.0f,   0.0f   },
  {  0.0f,      0.0f,   0.0f,   4.1f,   0.0f   },
  {  0.0f,      0.0f,   0.0f,   0.0f,  10.25f  },
};

static inline bool canNear(float a, float b, float tol) { return fabsf(a - b) <= tol; }

// Returns the number of failed checks; *first_fail gets the 1-based check
// number of the first failure (0 if none).
static inline uint16_t canProtoSelfTest(uint16_t* first_fail) {
  uint16_t fails = 0, n = 0;
  if (first_fail) *first_fail = 0;
#define CAN_CHECK(cond) do { n++; if (!(cond)) { if (!fails && first_fail) *first_fail = n; fails++; } } while (0)

  // 1. CMD: golden bytes, then round trip within half an LSB per field.
  for (const CanCmdVector& v : CAN_CMD_VECTORS) {
    uint8_t b[8];
    CAN_CHECK(canPackCmd(v.c, b));
    CAN_CHECK(memcmp(b, v.bytes, 8) == 0);
    MitCmd d;
    canUnpackCmd(v.bytes, d);
    CAN_CHECK(canNear(d.p_des_rad,      v.c.p_des_rad,      0.5001f * CAN_LSB_P_DES));
    CAN_CHECK(canNear(d.v_des_rads,     v.c.v_des_rads,     0.5001f * CAN_LSB_V_DES));
    CAN_CHECK(canNear(d.kp_Nm_per_rad,  v.c.kp_Nm_per_rad,  0.5001f * CAN_LSB_KP));
    CAN_CHECK(canNear(d.kd_Nms_per_rad, v.c.kd_Nms_per_rad, 0.5001f * CAN_LSB_KD));
    CAN_CHECK(canNear(d.tau_ff_Nm,      v.c.tau_ff_Nm,      0.5001f * CAN_LSB_TAU_FF));
  }
  // 2. Exact zero decodes to exact zero (not half an LSB).
  {
    MitCmd d; const uint8_t z[8] = { 0 };
    canUnpackCmd(z, d);
    CAN_CHECK(d.p_des_rad == 0.0f && d.v_des_rads == 0.0f && d.kp_Nm_per_rad == 0.0f
              && d.kd_Nms_per_rad == 0.0f && d.tau_ff_Nm == 0.0f);
  }
  // 3. Field ends: most-negative codes sign-extend correctly.
  {
    const MitCmd lo = { -6.28299f, -40.96f, 0.0f, 0.0f, -10.24f };
    uint8_t b[8]; MitCmd d;
    CAN_CHECK(canPackCmd(lo, b));
    canUnpackCmd(b, d);
    CAN_CHECK(canNear(d.v_des_rads, -40.96f, 1e-4f));
    CAN_CHECK(canNear(d.tau_ff_Nm,  -10.24f, 1e-4f));
    CAN_CHECK(d.p_des_rad < -6.28f);
  }
  // 4. Rejects.
  for (const MitCmd& c : CAN_CMD_REJECTS) {
    uint8_t b[8];
    CAN_CHECK(!canPackCmd(c, b));
  }
  // 5. STATE: golden bytes and round trip.
  for (const CanStateVector& v : CAN_STATE_VECTORS) {
    uint8_t b[8];
    CAN_CHECK(canPackState(v.s, v.status, b));
    CAN_CHECK(memcmp(b, v.bytes, 8) == 0);
    MitState d; uint8_t st;
    canUnpackState(v.bytes, d, st);
    CAN_CHECK(canNear(d.p_rad,  v.s.p_rad,  0.5001f * CAN_LSB_P));
    CAN_CHECK(canNear(d.v_rads, v.s.v_rads, 0.5001f * CAN_LSB_V));
    CAN_CHECK(canNear(d.tau_Nm, v.s.tau_Nm, 0.5001f * CAN_LSB_TAU));
    CAN_CHECK(st == v.status);
  }
  // 6. STATE saturates (measurement), and a NaN packs as 0 and reports it.
  {
    const MitState big = { 100.0f, -70.0f, 20.0f };
    uint8_t b[8]; MitState d; uint8_t st;
    CAN_CHECK(canPackState(big, 0, b));
    canUnpackState(b, d, st);
    CAN_CHECK(canNear(d.p_rad,   83.88607f, 1e-4f));
    CAN_CHECK(canNear(d.v_rads, -65.536f,   1e-4f));
    CAN_CHECK(canNear(d.tau_Nm,  16.3835f,  1e-4f));
    const MitState bad = { NAN, 0.0f, 0.0f };
    CAN_CHECK(!canPackState(bad, 0, b));
    canUnpackState(b, d, st);
    CAN_CHECK(d.p_rad == 0.0f);
  }
  // 7. Status byte and STATUS frame.
  {
    const uint8_t s = canStatusByte(true, CAN_PHASE_DAMP, true, CAN_FAULT_ENCODER);
    CAN_CHECK(s == 0x7D);
    CAN_CHECK(canStArmed(s) && canStPhase(s) == CAN_PHASE_DAMP && canStClamped(s)
              && canStFault(s) == CAN_FAULT_ENCODER);
    const CanStatus a = { CAN_BUILD_TIER0, CAN_CONTRACT_VERSION, 0xDEADBEEFu, 3,
                          (uint8_t)(CAN_SF_UID_OK | CAN_SF_HSE_OK) };
    uint8_t b[8]; CanStatus d;
    canPackStatus(a, b);
    CAN_CHECK(b[0] == 'T' && b[2] == 0xEF && b[5] == 0xDE && b[6] == 3);
    canUnpackStatus(b, d);
    CAN_CHECK(d.git_hash == 0xDEADBEEFu && d.joint_id == 3 && d.flags == a.flags
              && d.contract_version == CAN_CONTRACT_VERSION);
  }
  // 8. IDs and node decoding.
  CAN_CHECK(canIdCmd(1) == 0x101 && canIdState(12) == 0x18C && canIdAdmin(3) == 0x013
            && canIdStatus(3) == 0x703);
  CAN_CHECK(canNodeOf(0x103, CAN_ID_CMD_BASE) == 3 && canNodeOf(0x100, CAN_ID_CMD_BASE) == 0
            && canNodeOf(0x10D, CAN_ID_CMD_BASE) == 0);
#undef CAN_CHECK
  return fails;
}
